### ISSUE TITLE
Closure Compiler punch list

### ISSUE THREAD

**Issue by hegemonic** [jsdoc3/jsdoc#605]
This issue tracks adding support for all of the documented [Google Closure Compiler annotations](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#jsdoc-tags).

**Tags**
- [x] `@const`
- [x] `@constructor`
- [x] `@define`
- [x] `@deprecated`
- [x] `@dict`
- [x] `@enum`
- [x] `@export`
- [x] `@extends`
- [x] `@externs`
- [x] `@fileoverview`
- [x] `@final`
- [x] `@implements` (#375)
- [x] `@implicitCast`
- [x] `@inheritDoc` (#53)
- [x] `@interface` (#375)
- [x] `@lends`
- [x] `@license`
- [x] `@modifies`
- [x] `@noalias`
- [x] `@nocollapse`
- [x] `@nocompile`
- [x] `@nosideeffects`
- [x] `@override` (#53)
- [x] `@package` (#962)
- [x] `@param`
- [x] `@polymer`
- [x] `@polymerBehavior`
- [x] `@preserve` (synonym for `@license`)
- [x] `@private` (needs to accept a type) (#730)
- [x] `@protected` (needs to accept a type) (#731)
- [x] `@public`
- [x] `@record` (partial synonym for `@interface`; see [Structural Interfaces in Closure Compiler](https://github.com/google/closure-compiler/wiki/Structural-Interfaces-in-Closure-Compiler) for details)
- [x] `@return`
- [x] `@struct`
- [x] `@suppress`
- [x] `@template` (#567)
- [x] `@this` (implemented, but with different semantics)
- [x] `@throws` 
- [x] `@type` (needs to accept a description) (#732)
- [x] `@typedef` (implemented, but with different semantics)
- [x] `@unrestricted`

**Other annotation**
- [x] Inline docs for function arguments (#473)
- [x] Generic types (#567)

**Miscellaneous**
- [ ] ~~Run JSDoc on Closure Library with 0 warnings~~
- [ ] ~~Generate useful documentation by running JSDoc on Closure Library~~

**Comment by kevinoid** [comment]
It would be nice to have these, but some are obviously very non-trivial to implement.  Is there a way we can suppress `The %s tag is not a known tag.` error for these when using the `closure` dictionary until they are implemented?  Perhaps a configuration option I've overlooked?

**Comment by hegemonic** [comment]
Fixed on master. JSDoc 3.6.0 will include support for the new tags.
