### ISSUE TITLE
Update to Espree 2.0

### ISSUE THREAD

**Issue by hegemonic** [jsdoc3/jsdoc#977]
This includes, at a minimum, the following breaking changes that we'll need to adapt to:

+ [x] Remove guardedHandlers/handlers from try (eslint/espree#71)
+ [x] Change rest parameters to implement ESTree (eslint/espree#84)
+ [x] implement ESTree default parameters (eslint/espree#114)
+ [x] Implement ESTree Super node (eslint/espree#115)

**Comment by hegemonic** [comment]
Fixed on master.

**Comment by kapouer** [comment]
Hello,
we're investigating the dependencies of jsdoc for making a debian package.
Doing so, i don't understand clearly why you moved to Espree.
Esprima doesn't look like it's dead, and so many modules depend on it.
We're trying to avoid packaging plural forks of a software, as you can understand, so i'm asking
to see if your answer can help me choose which one of Espree or Esprima should be packaged
in debian.
Thank you for your help.
